remote_theme: ddc-java/ddc-day
repository_links:
  enabled: true
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "Astronomy Pictures"
description: "An app to look at daily astronomy pictures"
author:
  name: "Royce Reano"

# Do not change the following line.
  copyright: true
